### ISSUE TITLE
Favicon.ico 401 Unauthorized

### ISSUE THREAD

**Issue by incrosnatubogdan** [cedevita/getheadlines#7]
Whenever I run the project I get  `favicon.ico:1 GET http://localhost:3028/favicon.ico 401 (Unauthorized)`
I added this to index.js, but still get a 401

`v1.get('/favicon.ico', function(reg,res){
	res.sendStatus(200);
});`

What exactly is causing this?

**Comment by cedevita** [comment]
I didn't add a favicon to HTML pages. 

You can solve it by adding blank `<link rel="shortcut icon" href="">`  to all html's, or by using Koa's [favicon middleware](https://github.com/koajs/favicon).

I will fix this once I add getHeadlines logo to the project, and close this issue.
