### ISSUE TITLE
Need help making the app work

### ISSUE THREAD

**Issue by incrosnatubogdan** [cedevita/getheadlines#8]
Hello, I've managed after almost a month to not get the previous issue, but now I'm wondering what exactly can I do in order to make it work?

My question is, after I've managed to log in, what do I need to do in order to send data to firebase?

**Comment by cedevita** [comment]
This question was about the first version, written in Koa. It's been refactored and is not using Koa / Firebase anymore. Therefore I'm closing this issue.
